# Generated by Django 5.2.6 on 2025-09-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='randcode',
            new_name='code',
        ),
    ]
