# Generated by Django 5.2.6 on 2025-09-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pricr',
            new_name='price',
        ),
    ]
